export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";